//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _21._102_11_Pharmacy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public int employee_id { get; set; }
        public int user_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public int position_id { get; set; }
        public string phone_number { get; set; }
        public string passport_series { get; set; }
        public string passport_number { get; set; }
    
        public virtual positions positions { get; set; }
        public virtual users users { get; set; }
    }
}
