//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _21._102_11_Pharmacy.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<clients> clients { get; set; }
        public DbSet<deliveries> deliveries { get; set; }
        public DbSet<employees> employees { get; set; }
        public DbSet<orderdetails> orderdetails { get; set; }
        public DbSet<orders> orders { get; set; }
        public DbSet<pharmacyproducts> pharmacyproducts { get; set; }
        public DbSet<positions> positions { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<supplierdeliveries> supplierdeliveries { get; set; }
        public DbSet<suppliers> suppliers { get; set; }
        public DbSet<users> users { get; set; }
    }
}
