//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _21._102_11_Pharmacy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class suppliers
    {
        public suppliers()
        {
            this.deliveries = new HashSet<deliveries>();
        }
    
        public int supplier_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone_number { get; set; }
    
        public virtual ICollection<deliveries> deliveries { get; set; }
    }
}
